#! /usr/bin/env zsh
#
## default layout (can be bsp, stack or float)
yabai -m config layout bsp
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding set to 12px
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

yabai -m config mouse_follows_focus off
# focus follows mouse - hypr default
# yabai -m config focus_follows_mouse on

# modifier for clicking and dragging with mouse
# yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize


# yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
# focus -change borders
# yabai -m signal --add event=window_focused \
#      action=~/.config/borders/diffborders

function toggle_border_color_window() {
# gets window ID, set different borders for fullscreen/parent-zoom/default
  windowID=$1
  sleep 0.1
  if $(yabai -m query --windows --window |jq '."has-fullscreen-zoom"'); then
    borders active_color=0xffff0000 apply-to=${windowID}
  elif $(yabai -m query --windows --window |jq '."has-parent-zoom"'); then
    borders active_color=0xffab47bc apply-to=${windowID}
  else
    borders active_color=0xffff7600 apply-to=${windowID}
  fi
}

yabai -m signal --add event=window_resized \
   action="~/.config/yabai/toggleborders.sh \$YABAI_WINDOW_ID"

yabai -m signal --add event=window_destroyed \
  action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"
yabai -m signal --add event=window_minimized \
  action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"
yabai -m signal --add event=application_hidden \
  action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

