# this files should be in /etc/keyd/ directory
# keyd should be installed https://github.com/rvaiya/keyd
[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
#capslock = overload(control, esc)

# Remaps the escape key to capslock
#esc = capslock
#remaps super+c/v/f to ctrl+c/v/f - to make it same as on macOS
# also check app.conf - additional remaps for terminal, to have same keys across all apps
[meta]
c = C-c
v = C-v
f = C-f
