import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]

[font]
normal = { family = "JetBrains Mono", style = "Light"}
bold = { style = "Regular" }
size = 11.25

[window]
# option_as_alt = "Both"
dimensions = { columns = 159, lines = 73 }
padding = { x = 2 , y = 2 }
position = { x = 1283, y = 0 }
