import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]

[font]
normal = { family = "JetBrains Mono", style = "Light"}
bold = { style = "Regular" }
size = 11

[window]
# option_as_alt = "Both"
dimensions = { columns = 140, lines = 68 }
padding = { x = 2 , y = 2 }
position = { x = 1286, y = 0 }
decorations = "None"

[keyboard]
bindings = [
{ key = "V", mods = "Control", action = "Paste"},
]
